config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :profiles, except: [:index]
    # collection do
    #   get 'states'
    # end
  # end

  resources :blogs
  root 'home#index'
  # get 'cities/:state', to: 'application#cities'

  resources :cities, only: :index
  resources :states, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :authentication_keys => [:login]
  has_one :profile, :dependent => :destroy
  has_many :blogs, :dependent => :destroy

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["username = :value OR email = :value", { :value => login }]).first
    else
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  # def cities
  #   render json: CS.cities(params[:state], :IN).to_json
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone, :email])
    # devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email, :phone, :password])
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :phone)}
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.profile.present?
      @blogs = Blog.all
    else
      redirect_to root_path, notice: "Please create your profile first"
    end
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)

    if @blog.save
      respond_to do |format|
        # format.html { edirect_to blogs_url, notice: 'Blog was successfully created' }
        format.js
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      respond_to do |format|
      # format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed'}
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      # format.html { redirect_to root_path, notice: 'Blog was successfully destroyed'}
      format.js
    end
  end

  private
    def blog_params
      params.require(:blog).permit(:name, :image, :description, :launch_date)
    end

    def set_blog
      @blog = Blog.find(params[:id])
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = CS.get(params[:country], params[:state])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, except: [:new, :create]

  def show
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.create_profile(profile_params)
    if @profile.save
      respond_to do |format|
        format.html { redirect_to @profile, notice: 'Profile was successfully created' }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      respond_to do |format|
        format.html { redirect_to @profile, notice: 'Profile was successfully updated' }
        # format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    respond_to do |format|
      # format.html { redirect_to root_path, notice: 'Profile was successfully destroyed'}
      format.js
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :image, :country, :state, :city)
    end

    def set_profile
      @profile = Profile.find(params[:id])
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = CS.states(params[:country])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/blogs/_blog.html.erb
<tr id="row_<%= blog.id%>">
  <td><%= blog.name %></td>
  <td>
    <% if blog.image.attached? %>
      <%= image_tag blog.image ,size: "150x150"%>
    <% end %>
  </td>
  <td><%= blog.description %></td>
  <td><%= blog.launch_date %></td>
  <td id="row_<%= blog.id%>"><%= link_to "Edit Blog", edit_blog_path(blog), remote: true, :class => "button btn btn-info click-on"%></td>
  <td id="column_<%= blog.id%>"><%= link_to "Show Blog", blog_path(blog), remote: true, :class => "button btn btn-primary"%></td>
  <td><%= link_to "Delete Blog", blog_path(blog), method: :delete, remote: true, :class => "button btn btn-danger click-on"%></td>
</tr>

app/views/blogs/_form.html.erb
<%= bootstrap_form_with model:@blog, local: false do |form| %>
  <%= form.text_field :name %>
  <%= form.file_field :image %>
  <%= form.text_area :description %>
  <%= form.date_field :launch_date %>
  <%= form.submit %>
<% end %>

app/views/blogs/_show.html.erb
<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Image:</strong>
    <% if @blog.image.attached? %>
      <%= image_tag @blog.image ,size: "150x150" %>
    <% end %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Launch Date:</strong>
  <%= @blog.launch_date %>
</p>

app/views/blogs/create.js.erb
$("#new_blog form").remove();
$("#blogs").append("<%= j render @blog %>");

app/views/blogs/destroy.js.erb
$("#row_<%= escape_javascript params[:id] %>").remove();

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render "form" %><br>
<%= link_to 'Back', blogs_path, :class => "button btn btn-primary" %>

app/views/blogs/edit.js.erb
$("td#row_<%= @blog.id%> a").replaceWith("<%= j render 'form' %>")

app/views/blogs/index.html.erb
<div id = 'new_blog'>
  <%= link_to "New", new_blog_path, :class => "button btn btn-success", remote: true %>
</div>
<br>

<div class="col-md-12 col-md-offset-12 space-between">
  <table class="table" id="blogs">
    <thead>
      <tr>
        <th>Name</th>
        <th><center>Image</center></th>
        <th>Description</th>
        <th>Launch Date</th>
        <th><center>Action</center></th>
      </tr>
    </thead>
    <tbody>
        <% @blogs.each do |blog| %>
          <%= render partial: 'blog', locals:{blog: blog} %>
        <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Back", root_path, :class => "button btn btn-primary"%>

app/views/blogs/new.html.erb
<h1>Create Blog</h1>

<%= render "form" %><br>
<%= link_to 'Back', blogs_path, :class => "button btn btn-primary" %>

app/views/blogs/new.js.erb
$("#new_blog a").parent().append("<%= j render 'form' %>")

app/views/blogs/show.js.erb
$("td#column_<%= @blog.id%> a").replaceWith("<%= j render 'show' %>")

app/views/blogs/update.js.erb
$("tr#row_<%= @blog.id%> form").remove();
$("tr#row_<%= @blog.id%>").replaceWith("<%= j render @blog %>");

app/views/cities/index.js.erb
// Find the state select box
var city = document.getElementById("profile_city");

// Clear the options in the select box
while (city.firstChild) city.removeChild(city.firstChild);

// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a city";
placeholder.value = "";
city.appendChild(placeholder);

// Add the states
<% @cities.each do |c| %>
    city.options[city.options.length] = new Option('<%= c %>');
<% end %>

app/views/home/index.html.erb
<%#unless current_user.profile.present? %>
  <div id = 'new_profile'>
    <%= link_to "CreateProfile", new_profile_path, :class => 'navbar-brand' %>
  </div>
<%#end %>

<div class="col-md-12 col-md-offset-12">
  <table class="table" id="profile">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th><center>Image</center></th>
        <th>Country</th>
        <th>State</th>
        <th>City</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'profiles/profile', locals:{profile: current_user.profile} %>
    </tbody>
  </table>
</div>


<br><br><br>
<center><h1><%= link_to "Click here to see All Blogs", blogs_path %></h1></center>

<%= image_tag("blog.png", size: "500x400") %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <% if user_signed_in? %>
          <%= link_to "Edit Registration", edit_user_registration_path, :class => 'navbar-brand' %>
          <%= link_to "LogOut", destroy_user_session_path, method: :delete, :class => 'navbar-brand' %>
          <%= link_to current_user.email, :class => 'navbar-brand' %>
        <% else %>
          <%= link_to "SignUp", new_user_registration_path, :class => 'navbar-brand' %>
          <%= link_to "LogIn", new_user_session_path, :class => 'navbar-brand' %>
        <% end %>
        <% if user_signed_in? && current_user.profile.present? %>
          <%= link_to "ShowProfile", profile_path(current_user.profile), :class => 'navbar-brand' %>
          <%= link_to "EditProfile", edit_profile_path(current_user.profile), :class => 'navbar-brand'%>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <center><%= content_tag :div, msg, class: "alert alert-info" %></center>
    <% end %>
    <%= render 'layouts/navbar' %>
    <div class ='container-fluid'>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= bootstrap_form_with model: @profile, local: false do |form| %>
  <%= form.text_field :firstname %>
  <%= form.text_field :lastname %><br>
  <%= form.file_field :image %>
  <%= form.select :country, options_for_select(CS.countries.map { |c| [c[1], c[0]] } ) %><br>
  <%= form.select :state, options_for_select([]) %><br>
  <%= form.select :city, options_for_select([]) %>

  <%= form.submit %>
<% end %>

app/views/profiles/_profile.html.erb
<% if current_user.profile.present? %>
  <tr id="row_<%= current_user.profile.id%>">
    <td><%= current_user.profile.firstname %></td>
    <td><%= current_user.profile.lastname %></td>
    <td>
      <% if current_user.profile.image.attached? %>
        <%= image_tag current_user.profile.image ,size: "250x150"%>
      <%end %>
    </td>
    <td><%= current_user.profile.country %></td>
    <td><%= current_user.profile.state %></td>
    <td><%= current_user.profile.city %></td>
    <!-- <td id="row_<%#= current_user.profile.id%>"><%#= link_to "Edit my profile", edit_profile_path(current_user.profile), remote: true, :class => "button btn btn-primary" %></td> -->
    <td><%= link_to "Delete my profile", profile_path(current_user.profile), method: :delete, remote: true, :class => "button btn btn-danger" %></td>
  </tr>
<% end %>

app/views/profiles/create.js.erb
$("#new_profile form").remove()
$("#profile").append("<%= j render 'profiles/profile' %>")

app/views/profiles/destroy.js.erb
$("#row_<%= escape_javascript params[:id] %>").remove();

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<%= render "form" %><br>
<%= link_to 'Back', root_path, :class => "button btn btn-primary" %>

app/views/profiles/edit.js.erb
$("td#row_<%= current_user.profile.id%> a").replaceWith("<%= j render 'form' %>")

app/views/profiles/new.html.erb
<h1>Create Profile</h1>

<%= render "form" %>

app/views/profiles/new.js.erb
$("#new_profile a").parent().append("<%= j render 'form' %>")

app/views/profiles/show.html.erb
<div class="col-md-12 col-md-offset-12">
  <table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th><center>Image</center></th>
        <th>Country</th>
        <th>State</th>
        <th>City</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @profile.firstname %></td>
        <td><%= @profile.lastname %></td>
        <td>
          <% if @profile.image.attached? %>
            <%= image_tag @profile.image ,size: "350x250"%>
          <% end %>
        </td>
        <td><%= @profile.country %></td>
        <td><%= @profile.state %></td>
        <td><%= @profile.city %></td>
        <td><%= link_to "Delete my profile", profile_path(current_user.profile), method: :delete, remote: true, :class => "button btn btn-danger" %></td>
      </tr>
    </tbody>
  </table>
</div>
<%= link_to 'Back', root_path, :class => "button btn btn-primary" %>

app/views/profiles/update.js.erb
$("tr#row_<%= current_user.profile.id%> form").remove();
$("tr#row_<%= current_user.profile.id%>").replaceWith("<%= j render @profile %>");

app/views/states/index.js.erb
// Find the state select box
var state = document.getElementById("profile_state");

// Clear the options in the select box
while (state.firstChild) state.removeChild(state.firstChild);

// Add a placeholder
var placeholder = document.createElement("option");
placeholder.text = "Choose a state";
placeholder.value = "";
placeholder.placeholder = true;
state.appendChild(placeholder);

// Add the states
<% @states.each do |s| %>
  state.options[state.options.length] = new Option('<%= s[1] %>', '<%= s[0] %>')
<% end %>